{{
  config(
    materialized='table',
    schema=var('silver_dataset'),
    alias='idi_transformed_data_2024'
  )
}}

-- Modelo 2024: Selecciona columnas con COALESCE para NULL → 0 en numéricas

SELECT
  -- Columnas base
  CAST(codigo_sigep AS STRING) AS codigo_sigep,
  entidad,
  orden,
  clasificacion_organica,
  naturaleza_juridica,
  sector,
  departamento,
  municipio,
  pdet,
  COALESCE(SAFE_CAST(capital AS FLOAT64), 0) AS capital,
  COALESCE(CAST(NULL AS INT64),0) AS id_grupo_par,
  grupo_par,
  tipo_formulario,
  
  -- Índice y dimensiones (con COALESCE)
  COALESCE(SAFE_CAST(indice_de_desempeno_institucional AS FLOAT64), 0) AS indice_de_desempeno_institucional,
  COALESCE(SAFE_CAST(d1_talento_humano AS FLOAT64), 0) AS d1_talento_humano,
  COALESCE(SAFE_CAST(d2_direcciona_miento_estrategico_y_planeacion AS FLOAT64), 0) AS d2_direcciona_miento_estrategico_y_planeacion,
  COALESCE(SAFE_CAST(d3_gestion_para_resultados_con_valores AS FLOAT64), 0) AS d3_gestion_para_resultados_con_valores,
  COALESCE(SAFE_CAST(d4_evaluacion_de_resultados AS FLOAT64), 0) AS d4_evaluacion_de_resultados,
  COALESCE(SAFE_CAST(d5_informacion_y_comunicacion AS FLOAT64), 0) AS d5_informacion_y_comunicacion,
  COALESCE(SAFE_CAST(d6_gestion_del_conocimiento AS FLOAT64), 0) AS d6_gestion_del_conocimiento,
  COALESCE(SAFE_CAST(d7_control_interno AS FLOAT64), 0) AS d7_control_interno,
  
  -- Políticas e indicadores (con COALESCE)
  COALESCE(SAFE_CAST(pol01_indice_de_gestion_estrategica_del_talento_humano AS FLOAT64), 0) AS pol01_indice_de_gestion_estrategica_del_talento_humano,
  COALESCE(SAFE_CAST(i01_calidad_de_la_planeacion_estrategica_del_talento_humano AS FLOAT64), 0) AS i01_calidad_de_la_planeacion_estrategica_del_talento_humano,
  COALESCE(SAFE_CAST(i02_eficiencia_y_eficacia_de_la_seleccion_meritocratica_del_talento_humano AS FLOAT64), 0) AS i02_eficiencia_y_eficacia_de_la_seleccion_meritocratica_del_talento_humano,
  COALESCE(SAFE_CAST(i03_desarrollo_del_talento_humano_en_la_entidad AS FLOAT64), 0) AS i03_desarrollo_del_talento_humano_en_la_entidad,
  COALESCE(SAFE_CAST(i04_desvinculacion_asistida_y_retencion_del_conocimiento_generado_por_el_talento_humano AS FLOAT64), 0) AS i04_desvinculacion_asistida_y_retencion_del_conocimiento_generado_por_el_talento_humano,
  COALESCE(SAFE_CAST(pol02_indice_de_integridad AS FLOAT64), 0) AS pol02_indice_de_integridad,
  COALESCE(SAFE_CAST(i05_cambio_cultural_basado_en_la_implementacion_del_codigo_de_integridad_del_servicio_publico AS FLOAT64), 0) AS i05_cambio_cultural_basado_en_la_implementacion_del_codigo_de_integridad_del_servicio_publico,
  COALESCE(SAFE_CAST(i06_gestion_adecuada_de_acciones_preventivas_en_conflicto_de_interes AS FLOAT64), 0) AS i06_gestion_adecuada_de_acciones_preventivas_en_conflicto_de_interes,
  COALESCE(SAFE_CAST(i07_coherencia_entre_los_elementos_que_materializan_la_integridad_en_el_servicio_publico_y_la_gestion_del_riesgo_y_control AS FLOAT64), 0) AS i07_coherencia_entre_los_elementos_que_materializan_la_integridad_en_el_servicio_publico_y_la_gestion_del_riesgo_y_control,
  COALESCE(SAFE_CAST(pol03_indice_de_planeacion_institucional AS FLOAT64), 0) AS pol03_indice_de_planeacion_institucional,
  COALESCE(SAFE_CAST(pol04_indice_de_gestion_presupuestal_y_eficiencia_del_gasto_publico AS FLOAT64), 0) AS pol04_indice_de_gestion_presupuestal_y_eficiencia_del_gasto_publico,
  COALESCE(SAFE_CAST(pol05_indice_de_compras_y_contratacion_publica AS FLOAT64), 0) AS pol05_indice_de_compras_y_contratacion_publica,
  COALESCE(SAFE_CAST(i08_planeacion_efectiva_y_tecnica_de_la_contratacion_publica AS FLOAT64), 0) AS i08_planeacion_efectiva_y_tecnica_de_la_contratacion_publica,
  COALESCE(SAFE_CAST(i09_registro_y_publicacion_contractual_en_las_plataformas AS FLOAT64), 0) AS i09_registro_y_publicacion_contractual_en_las_plataformas,
  COALESCE(SAFE_CAST(i10_aplicacion_de_lineamientos_normativos_documentos_estandar_e_instrumentos AS FLOAT64), 0) AS i10_aplicacion_de_lineamientos_normativos_documentos_estandar_e_instrumentos,
  COALESCE(SAFE_CAST(pol06_indice_de_fortalecimiento_organizacional_y_simplificacion_de_procesos AS FLOAT64), 0) AS pol06_indice_de_fortalecimiento_organizacional_y_simplificacion_de_procesos,
  COALESCE(SAFE_CAST(pol07_indice_de_gobierno_digital AS FLOAT64), 0) AS pol07_indice_de_gobierno_digital,
  COALESCE(SAFE_CAST(i11_gobernanza AS FLOAT64), 0) AS i11_gobernanza,
  COALESCE(SAFE_CAST(i12_innovacion_publica_digital AS FLOAT64), 0) AS i12_innovacion_publica_digital,
  COALESCE(SAFE_CAST(i13_arquitectura AS FLOAT64), 0) AS i13_arquitectura,
  COALESCE(SAFE_CAST(i14_seguridad_y_privacidad_de_la_informacion AS FLOAT64), 0) AS i14_seguridad_y_privacidad_de_la_informacion,
  COALESCE(SAFE_CAST(i15_servicios_ciudadanos_digitales AS FLOAT64), 0) AS i15_servicios_ciudadanos_digitales,
  COALESCE(SAFE_CAST(i16_cultura_y_apropiacion AS FLOAT64), 0) AS i16_cultura_y_apropiacion,
  COALESCE(SAFE_CAST(i17_servicios_y_procesos_inteligentes AS FLOAT64), 0) AS i17_servicios_y_procesos_inteligentes,
  COALESCE(SAFE_CAST(i18_estado_abierto AS FLOAT64), 0) AS i18_estado_abierto,
  COALESCE(SAFE_CAST(i19_decisiones_basadas_en_datos AS FLOAT64), 0) AS i19_decisiones_basadas_en_datos,
  COALESCE(SAFE_CAST(i20_proyectos_de_transformacion_digital AS FLOAT64), 0) AS i20_proyectos_de_transformacion_digital,
  COALESCE(SAFE_CAST(i21_estrategias_de_ciudades_y_territorios_inteligentes AS FLOAT64), 0) AS i21_estrategias_de_ciudades_y_territorios_inteligentes,
  COALESCE(SAFE_CAST(pol08_indice_de_seguridad_digital AS FLOAT64), 0) AS pol08_indice_de_seguridad_digital,
  COALESCE(SAFE_CAST(i22_asigancion_de_recursos AS FLOAT64), 0) AS i22_asigancion_de_recursos,
  COALESCE(SAFE_CAST(i23_implementacion_lineamientos_de_politica AS FLOAT64), 0) AS i23_implementacion_lineamientos_de_politica,
  COALESCE(SAFE_CAST(i24_despliegue_de_controles AS FLOAT64), 0) AS i24_despliegue_de_controles,
  COALESCE(SAFE_CAST(pol09_indice_defensa_juridica AS FLOAT64), 0) AS pol09_indice_defensa_juridica,
  COALESCE(SAFE_CAST(i70_prevencion_del_dano_antijuridico AS FLOAT64), 0) AS i70_prevencion_del_dano_antijuridico,
  COALESCE(SAFE_CAST(i25_gestion_de_las_actuaciones_prejudiciales AS FLOAT64), 0) AS i25_gestion_de_las_actuaciones_prejudiciales,
  COALESCE(SAFE_CAST(i26_gestion_de_la_defensa_judicial AS FLOAT64), 0) AS i26_gestion_de_la_defensa_judicial,
  COALESCE(SAFE_CAST(i27_gestion_del_cumplimento_de_sentencias_y_conciliaciones AS FLOAT64), 0) AS i27_gestion_del_cumplimento_de_sentencias_y_conciliaciones,
  COALESCE(SAFE_CAST(i28_gestion_de_la_accion_de_repeticion AS FLOAT64), 0) AS i28_gestion_de_la_accion_de_repeticion,
  COALESCE(SAFE_CAST(i29_gestion_del_conocimiento_juridico AS FLOAT64), 0) AS i29_gestion_del_conocimiento_juridico,
  COALESCE(SAFE_CAST(pol10_indice_mejora_normativa AS FLOAT64), 0) AS pol10_indice_mejora_normativa,
  COALESCE(SAFE_CAST(i30_planeacion_y_diseno_de_los_actos_administrativos_de_caracter_general AS FLOAT64), 0) AS i30_planeacion_y_diseno_de_los_actos_administrativos_de_caracter_general,
  COALESCE(SAFE_CAST(i31_redaccion_consulta_publica_y_revision_de_los_actos_administrativos_de_caracter_general AS FLOAT64), 0) AS i31_redaccion_consulta_publica_y_revision_de_los_actos_administrativos_de_caracter_general,
  COALESCE(SAFE_CAST(i32_publicacion_y_evaluacion_de_los_actos_administrativos AS FLOAT64), 0) AS i32_publicacion_y_evaluacion_de_los_actos_administrativos,
  COALESCE(SAFE_CAST(pol11_indice_de_servicio_a_las_ciudadanias AS FLOAT64), 0) AS pol11_indice_de_servicio_a_las_ciudadanias,
  COALESCE(SAFE_CAST(i33_diagnostico_y_planeacion_del_servicio_y_relacionamiento_con_la_ciudadania AS FLOAT64), 0) AS i33_diagnostico_y_planeacion_del_servicio_y_relacionamiento_con_la_ciudadania,
  COALESCE(SAFE_CAST(i34_talento_humano_idoneo_y_suficiente_al_servicio_y_relacionamiento_con_la_ciudadania AS FLOAT64), 0) AS i34_talento_humano_idoneo_y_suficiente_al_servicio_y_relacionamiento_con_la_ciudadania,
  COALESCE(SAFE_CAST(i35_oferta_institucional_de_facil_acceso_comprension_y_uso_para_la_ciudadania AS FLOAT64), 0) AS i35_oferta_institucional_de_facil_acceso_comprension_y_uso_para_la_ciudadania,
  COALESCE(SAFE_CAST(i36_evaluacion_de_la_gestion_del_servicio_y_medicion_de_la_experiencia_ciudadana AS FLOAT64), 0) AS i36_evaluacion_de_la_gestion_del_servicio_y_medicion_de_la_experiencia_ciudadana,
  COALESCE(SAFE_CAST(i37_accesibilidad_para_personas_con_discapacidad AS FLOAT64), 0) AS i37_accesibilidad_para_personas_con_discapacidad,
  COALESCE(SAFE_CAST(pol12_indice_de_racionalizacion_de_tramites AS FLOAT64), 0) AS pol12_indice_de_racionalizacion_de_tramites,
  COALESCE(SAFE_CAST(i39_priorizacion_de_tramites_con_base_en_las_necesidades_y_expectativas_de_los_ciudadanos AS FLOAT64), 0) AS i39_priorizacion_de_tramites_con_base_en_las_necesidades_y_expectativas_de_los_ciudadanos,
  COALESCE(SAFE_CAST(i40_tramites_racionalizados_y_recursos_tenidos_en_cuenta_para_mejorarlos AS FLOAT64), 0) AS i40_tramites_racionalizados_y_recursos_tenidos_en_cuenta_para_mejorarlos,
  COALESCE(SAFE_CAST(i41_beneficios_de_las_acciones_de_racionalizacion_adelantadas AS FLOAT64), 0) AS i41_beneficios_de_las_acciones_de_racionalizacion_adelantadas,
  COALESCE(SAFE_CAST(pol13_indice_de_participacion_ciudadana_en_la_gestion_publica AS FLOAT64), 0) AS pol13_indice_de_participacion_ciudadana_en_la_gestion_publica,
  COALESCE(SAFE_CAST(i42_capacidades_institucionales_instaladas_para_la_promocion_de_la_participacion AS FLOAT64), 0) AS i42_capacidades_institucionales_instaladas_para_la_promocion_de_la_participacion,
  COALESCE(SAFE_CAST(i43_planeacion_anual_de_la_estrategia_de_participacion_ciudadana_en_la_geston_publica AS FLOAT64), 0) AS i43_planeacion_anual_de_la_estrategia_de_participacion_ciudadana_en_la_geston_publica,
  COALESCE(SAFE_CAST(i44_implementacion_de_acciones_de_participacion_ciudadana_en_las_diferentes_fases_del_ciclo_de_gestion AS FLOAT64), 0) AS i44_implementacion_de_acciones_de_participacion_ciudadana_en_las_diferentes_fases_del_ciclo_de_gestion,
  COALESCE(SAFE_CAST(i45_capacidad_de_involucrar_efectivamente_a_los_diferentes_grupos_poblacionales_en_las_acciones_de_participacion_garantizando_el AS FLOAT64), 0) AS i45_capacidad_de_involucrar_efectivamente_a_los_diferentes_grupos_poblacionales_en_las_acciones_de_participacion_garantizando_el,
  COALESCE(SAFE_CAST(i46_evaluacion_de_los_resultados_de_la_estrategia_anual_de_participacion_ciudadana_y_su_aprovechamiento_en_acciones_de_mejora_in AS FLOAT64), 0) AS i46_evaluacion_de_los_resultados_de_la_estrategia_anual_de_participacion_ciudadana_y_su_aprovechamiento_en_acciones_de_mejora_in,
  COALESCE(SAFE_CAST(i47_rendicion_de_cuentas_en_la_gestion_publica AS FLOAT64), 0) AS i47_rendicion_de_cuentas_en_la_gestion_publica,
  COALESCE(SAFE_CAST(pol14_indice_de_seguimiento_y_evaluacion_del_desempeno_institucional AS FLOAT64), 0) AS pol14_indice_de_seguimiento_y_evaluacion_del_desempeno_institucional,
  COALESCE(SAFE_CAST(pol15_indice_transparencia_acceso_a_la_informacion_y_lucha_contra_la_corrupcion AS FLOAT64), 0) AS pol15_indice_transparencia_acceso_a_la_informacion_y_lucha_contra_la_corrupcion,
  COALESCE(SAFE_CAST(i48_gestion_de_riesgos_de_corrupcion AS FLOAT64), 0) AS i48_gestion_de_riesgos_de_corrupcion,
  COALESCE(SAFE_CAST(i49_indice_de_transparencia_y_acceso_a_la_informacion_publica AS FLOAT64), 0) AS i49_indice_de_transparencia_y_acceso_a_la_informacion_publica,
  COALESCE(SAFE_CAST(pol16_indice_de_gestion_documental AS FLOAT64), 0) AS pol16_indice_de_gestion_documental,
  COALESCE(SAFE_CAST(i50_calidad_del_componente_estrategico AS FLOAT64), 0) AS i50_calidad_del_componente_estrategico,
  COALESCE(SAFE_CAST(i51_calidad_del_componente_administracion_de_archivos AS FLOAT64), 0) AS i51_calidad_del_componente_administracion_de_archivos,
  COALESCE(SAFE_CAST(i52_calidad_del_componente_documental AS FLOAT64), 0) AS i52_calidad_del_componente_documental,
  COALESCE(SAFE_CAST(i53_calidad_del_componente_tecnologico AS FLOAT64), 0) AS i53_calidad_del_componente_tecnologico,
  COALESCE(SAFE_CAST(i54_calidad_del_componente_cultural AS FLOAT64), 0) AS i54_calidad_del_componente_cultural,
  COALESCE(SAFE_CAST(pol17_indice_de_gestion_informacion_estadistica AS FLOAT64), 0) AS pol17_indice_de_gestion_informacion_estadistica,
  COALESCE(SAFE_CAST(i55_indice_planeacion_estadistica AS FLOAT64), 0) AS i55_indice_planeacion_estadistica,
  COALESCE(SAFE_CAST(i56_indice_fortalecimiento_de_registros_administrativos AS FLOAT64), 0) AS i56_indice_fortalecimiento_de_registros_administrativos,
  COALESCE(SAFE_CAST(i57_indice_calidad_estadistica AS FLOAT64), 0) AS i57_indice_calidad_estadistica,
  COALESCE(SAFE_CAST(pol18_indice_de_gestion_del_conocimiento AS FLOAT64), 0) AS pol18_indice_de_gestion_del_conocimiento,
  COALESCE(SAFE_CAST(i58_planeacion_de_la_gestion_del_conocimiento_y_la_innovacion AS FLOAT64), 0) AS i58_planeacion_de_la_gestion_del_conocimiento_y_la_innovacion,
  COALESCE(SAFE_CAST(i59_generacion_y_produccion_del_conocimiento AS FLOAT64), 0) AS i59_generacion_y_produccion_del_conocimiento,
  COALESCE(SAFE_CAST(i60_generacion_de_herramientas_de_uso_y_apropiacion_del_conocimiento AS FLOAT64), 0) AS i60_generacion_de_herramientas_de_uso_y_apropiacion_del_conocimiento,
  COALESCE(SAFE_CAST(i61_generacion_de_una_cultura_de_propicia_para_la_gestion_del_conocimiento_y_la_innovacion AS FLOAT64), 0) AS i61_generacion_de_una_cultura_de_propicia_para_la_gestion_del_conocimiento_y_la_innovacion,
  COALESCE(SAFE_CAST(i62_analitica_institucional_para_la_toma_de_decisiones AS FLOAT64), 0) AS i62_analitica_institucional_para_la_toma_de_decisiones,
  COALESCE(SAFE_CAST(pol19_indice_de_control_interno AS FLOAT64), 0) AS pol19_indice_de_control_interno,
  COALESCE(SAFE_CAST(i63_ambiente_propicio_para_el_ejercicio_del_control AS FLOAT64), 0) AS i63_ambiente_propicio_para_el_ejercicio_del_control,
  COALESCE(SAFE_CAST(i64_evaluacion_estrategica_del_riesgo AS FLOAT64), 0) AS i64_evaluacion_estrategica_del_riesgo,
  COALESCE(SAFE_CAST(i65_actividades_de_control_efectivas AS FLOAT64), 0) AS i65_actividades_de_control_efectivas,
  COALESCE(SAFE_CAST(i66_informacion_y_comunicacion_relevante_y_oportuna_para_el_control AS FLOAT64), 0) AS i66_informacion_y_comunicacion_relevante_y_oportuna_para_el_control,
  COALESCE(SAFE_CAST(i67_actividades_de_monitoreo_sistematicas_y_orientadas_a_la_mejora AS FLOAT64), 0) AS i67_actividades_de_monitoreo_sistematicas_y_orientadas_a_la_mejora,
  COALESCE(SAFE_CAST(i68_evaluacion_independiente_al_sistema_de_control_interno AS FLOAT64), 0) AS i68_evaluacion_independiente_al_sistema_de_control_interno

FROM {{ source('bronze_idi', 'idi_raw_data_territorio_2024') }}