[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyimport"
version = "0.1.0"
description = "Plantilla local para Astro/Airflow + dbt + ValleDATA Pipelines"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "Jhon Jairo Vallejo", email = "jhon.jairo.vallejo@gmail.com" }
]
dependencies = [
    "xlrd>=2.0",
    "openpyxl>=3.1",
    "pysentimiento>=0.7.3",
    "pandas>=2.0",
    "google-cloud-bigquery>=3.0.0",
    "google-cloud-storage>=2.0.0",
    "apache-airflow>=2.8.0",
    "astronomer-cosmos>=1.9.0",
    "dbt-core>=1.8.0",
    "dbt-bigquery>=1.8.0",
    "requests>=2.31.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "ruff>=0.6",
]

[project.scripts]
pyimport = "pyimport.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.ruff]
line-length = 100
target-version = "py311"

