{{
  config(
    materialized='ephemeral',
    schema='silver_dpt_planeacion_municipal_dev'
  )
}}

-- Modelo para normalizar texto: eliminar acentos y convertir a mayúsculas
SELECT
    -- Identificadores: eliminar acentos y convertir a mayúsculas
    UPPER(TRANSLATE(LOWER(CAST(cod_mpio AS STRING)), 'áéíóúñÁÉÍÓÚÑ', 'aeiounAEIOUN')) AS cod_mpio,
    UPPER(TRANSLATE(LOWER(CAST(municipio AS STRING)), 'áéíóúñÁÉÍÓÚÑ', 'aeiounAEIOUN')) AS municipio,
    
    -- Resto de columnas sin cambios
    total,
    ipm_pobre_abs,
    ipm_no_pobre_abs,
    ipm_pobre_porc,
    ipm_no_pobre_porc,
    i1_con_privacion_abs,
    i1_sin_privacion_abs,
    i1_con_privacion_porc,
    i1_sin_privacion_porc,
    i2_con_privacion_abs,
    i2_sin_privacion_abs,
    i2_con_privacion_porc,
    i2_sin_privacion_porc,
    i3_con_privacion_abs,
    i3_sin_privacion_abs,
    i3_con_privacion_porc,
    i3_sin_privacion_porc,
    i4_con_privacion_abs,
    i4_sin_privacion_abs,
    i4_con_privacion_porc,
    i4_sin_privacion_porc,
    i5_con_privacion_abs,
    i5_sin_privacion_abs,
    i5_con_privacion_porc,
    i5_sin_privacion_porc,
    i6_con_privacion_abs,
    i6_sin_privacion_abs,
    i6_con_privacion_porc,
    i6_sin_privacion_porc,
    i7_con_privacion_abs,
    i7_sin_privacion_abs,
    i7_con_privacion_porc,
    i7_sin_privacion_porc,
    i8_con_privacion_abs,
    i8_sin_privacion_abs,
    i8_con_privacion_porc,
    i8_sin_privacion_porc,
    i9_con_privacion_abs,
    i9_sin_privacion_abs,
    i9_con_privacion_porc,
    i9_sin_privacion_porc,
    i10_con_privacion_abs,
    i10_sin_privacion_abs,
    i10_con_privacion_porc,
    i10_sin_privacion_porc,
    i11_con_privacion_abs,
    i11_sin_privacion_abs,
    i11_con_privacion_porc,
    i11_sin_privacion_porc,
    i12_con_privacion_abs,
    i12_sin_privacion_abs,
    i12_con_privacion_porc,
    i12_sin_privacion_porc,
    i13_con_privacion_abs,
    i13_sin_privacion_abs,
    i13_con_privacion_porc,
    i13_sin_privacion_porc,
    i14_con_privacion_abs,
    i14_sin_privacion_abs,
    i14_con_privacion_porc,
    i14_sin_privacion_porc,
    i15_con_privacion_abs,
    i15_sin_privacion_abs,
    i15_con_privacion_porc,
    i15_sin_privacion_porc,
    fecha_lectura
FROM {{ ref('ipm_transform_stg') }}


