{{
  config(
    materialized='view',
    schema='gdv_ipmv2_silver'
  )
}}

-- Modelo staging: lee de bronze y normaliza nombres de columnas a snake_case
SELECT
    cod_mpio,
    Municipio AS municipio,
    Total AS total,
    IPM_Pobre_Abs AS ipm_pobre_abs,
    IPM_No_Pobre_Abs AS ipm_no_pobre_abs,
    IPM_Pobre_Porc AS ipm_pobre_porc,
    IPM_No_Pobre_Porc AS ipm_no_pobre_porc,
    I1_Con_Privacion_Abs AS i1_con_privacion_abs,
    I1_Sin_Privacion_Abs AS i1_sin_privacion_abs,
    I1_Con_Privacion_Porc AS i1_con_privacion_porc,
    I1_Sin_Privacion_Porc AS i1_sin_privacion_porc,
    I2_Con_Privacion_Abs AS i2_con_privacion_abs,
    I2_Sin_Privacion_Abs AS i2_sin_privacion_abs,
    I2_Con_Privacion_Porc AS i2_con_privacion_porc,
    I2_Sin_Privacion_Porc AS i2_sin_privacion_porc,
    I3_Con_Privacion_Abs AS i3_con_privacion_abs,
    I3_Sin_Privacion_Abs AS i3_sin_privacion_abs,
    I3_Con_Privacion_Porc AS i3_con_privacion_porc,
    I3_Sin_Privacion_Porc AS i3_sin_privacion_porc,
    I4_Con_Privacion_Abs AS i4_con_privacion_abs,
    I4_Sin_Privacion_Abs AS i4_sin_privacion_abs,
    I4_Con_Privacion_Porc AS i4_con_privacion_porc,
    I4_Sin_Privacion_Porc AS i4_sin_privacion_porc,
    I5_Con_Privacion_Abs AS i5_con_privacion_abs,
    I5_Sin_Privacion_Abs AS i5_sin_privacion_abs,
    I5_Con_Privacion_Porc AS i5_con_privacion_porc,
    I5_Sin_Privacion_Porc AS i5_sin_privacion_porc,
    I6_Con_Privacion_Abs AS i6_con_privacion_abs,
    I6_Sin_Privacion_Abs AS i6_sin_privacion_abs,
    I6_Con_Privacion_Porc AS i6_con_privacion_porc,
    I6_Sin_Privacion_Porc AS i6_sin_privacion_porc,
    I7_Con_Privacion_Abs AS i7_con_privacion_abs,
    I7_Sin_Privacion_Abs AS i7_sin_privacion_abs,
    I7_Con_Privacion_Porc AS i7_con_privacion_porc,
    I7_Sin_Privacion_Porc AS i7_sin_privacion_porc,
    I8_Con_Privacion_Abs AS i8_con_privacion_abs,
    I8_Sin_Privacion_Abs AS i8_sin_privacion_abs,
    I8_Con_Privacion_Porc AS i8_con_privacion_porc,
    I8_Sin_Privacion_Porc AS i8_sin_privacion_porc,
    I9_Con_Privacion_Abs AS i9_con_privacion_abs,
    I9_Sin_Privacion_Abs AS i9_sin_privacion_abs,
    I9_Con_Privacion_Porc AS i9_con_privacion_porc,
    I9_Sin_Privacion_Porc AS i9_sin_privacion_porc,
    I10_Con_Privacion_Abs AS i10_con_privacion_abs,
    I10_Sin_Privacion_Abs AS i10_sin_privacion_abs,
    I10_Con_Privacion_Porc AS i10_con_privacion_porc,
    I10_Sin_Privacion_Porc AS i10_sin_privacion_porc,
    I11_Con_Privacion_Abs AS i11_con_privacion_abs,
    I11_Sin_Privacion_Abs AS i11_sin_privacion_abs,
    I11_Con_Privacion_Porc AS i11_con_privacion_porc,
    I11_Sin_Privacion_Porc AS i11_sin_privacion_porc,
    I12_Con_Privacion_Abs AS i12_con_privacion_abs,
    I12_Sin_Privacion_Abs AS i12_sin_privacion_abs,
    I12_Con_Privacion_Porc AS i12_con_privacion_porc,
    I12_Sin_Privacion_Porc AS i12_sin_privacion_porc,
    I13_Con_Privacion_Abs AS i13_con_privacion_abs,
    I13_Sin_Privacion_Abs AS i13_sin_privacion_abs,
    I13_Con_Privacion_Porc AS i13_con_privacion_porc,
    I13_Sin_Privacion_Porc AS i13_sin_privacion_porc,
    I14_Con_Privacion_Abs AS i14_con_privacion_abs,
    I14_Sin_Privacion_Abs AS i14_sin_privacion_abs,
    I14_Con_Privacion_Porc AS i14_con_privacion_porc,
    I14_Sin_Privacion_Porc AS i14_sin_privacion_porc,
    I15_Con_Privacion_Abs AS i15_con_privacion_abs,
    I15_Sin_Privacion_Abs AS i15_sin_privacion_abs,
    I15_Con_Privacion_Porc AS i15_con_privacion_porc,
    I15_Sin_Privacion_Porc AS i15_sin_privacion_porc,
    fecha_lectura
FROM {{ source('bronze_ipmv2', 'rawdata_ipmv2') }}

